-- CostOps Native App
-- Step 1: provider-side bootstrap
--
-- Replace the placeholders below before running.

USE ROLE ACCOUNTADMIN;

SET PACKAGE_DB = 'COSTOPS_NATIVE_DEV';
SET PACKAGE_SCHEMA = 'PACKAGE_SRC';
SET PACKAGE_STAGE = 'COSTOPS_STAGE';
SET APPLICATION_PACKAGE_NAME = 'COSTOPS_PKG';
SET TEST_INSTALL_ROLE = 'ACCOUNTADMIN';

CREATE OR REPLACE DATABASE IDENTIFIER($PACKAGE_DB);
CREATE OR REPLACE SCHEMA IDENTIFIER($PACKAGE_DB || '.' || $PACKAGE_SCHEMA);

CREATE OR REPLACE STAGE IDENTIFIER($PACKAGE_DB || '.' || $PACKAGE_SCHEMA || '.' || $PACKAGE_STAGE);

CREATE APPLICATION PACKAGE IF NOT EXISTS IDENTIFIER($APPLICATION_PACKAGE_NAME)
  DISTRIBUTION = INTERNAL;

GRANT INSTALL ON APPLICATION PACKAGE IDENTIFIER($APPLICATION_PACKAGE_NAME)
  TO ROLE IDENTIFIER($TEST_INSTALL_ROLE);

SHOW APPLICATION PACKAGES LIKE $APPLICATION_PACKAGE_NAME;
SHOW STAGES LIKE $PACKAGE_STAGE IN SCHEMA IDENTIFIER($PACKAGE_DB || '.' || $PACKAGE_SCHEMA);
