-- CostOps Native App
-- Step 2: add a version and set the default release directive
--
-- Replace the placeholders below before running.

USE ROLE ACCOUNTADMIN;

SET PACKAGE_DB = 'COSTOPS_NATIVE_DEV';
SET PACKAGE_SCHEMA = 'PACKAGE_SRC';
SET PACKAGE_STAGE = 'COSTOPS_STAGE';
SET APPLICATION_PACKAGE_NAME = 'COSTOPS_PKG';
SET VERSION_NAME = 'V0_1';

EXECUTE IMMEDIATE
  'ALTER APPLICATION PACKAGE ' || $APPLICATION_PACKAGE_NAME ||
  ' ADD VERSION ' || $VERSION_NAME ||
  ' USING ''@' || $PACKAGE_DB || '.' || $PACKAGE_SCHEMA || '.' || $PACKAGE_STAGE || '''' ||
  ' LABEL = ''CostOps native validation v0.1''';

EXECUTE IMMEDIATE
  'ALTER APPLICATION PACKAGE ' || $APPLICATION_PACKAGE_NAME ||
  ' SET DEFAULT RELEASE DIRECTIVE VERSION = ' || $VERSION_NAME || ' PATCH = 0';

SHOW VERSIONS IN APPLICATION PACKAGE IDENTIFIER($APPLICATION_PACKAGE_NAME);
SHOW RELEASE DIRECTIVES IN APPLICATION PACKAGE IDENTIFIER($APPLICATION_PACKAGE_NAME);
