-- CostOps Native App
-- Step 3: create the development-mode app install
--
-- Replace the placeholders below before running.

USE ROLE ACCOUNTADMIN;

SET APPLICATION_PACKAGE_NAME = 'COSTOPS_PKG';
SET APPLICATION_NAME = 'COSTOPS_APP_DEV';
SET VERSION_NAME = 'V0_1';

EXECUTE IMMEDIATE
  'CREATE OR REPLACE APPLICATION ' || $APPLICATION_NAME ||
  ' FROM APPLICATION PACKAGE ' || $APPLICATION_PACKAGE_NAME ||
  ' USING VERSION ' || $VERSION_NAME;

SHOW APPLICATIONS LIKE $APPLICATION_NAME;
DESCRIBE APPLICATION IDENTIFIER($APPLICATION_NAME);
