-- CostOps Native App
-- Step 4: validate the local install
--
-- Replace the placeholders below before running.

USE ROLE ACCOUNTADMIN;

SET APPLICATION_NAME = 'COSTOPS_APP_DEV';

SHOW APPLICATIONS LIKE $APPLICATION_NAME;
DESCRIBE APPLICATION IDENTIFIER($APPLICATION_NAME);
SHOW APPLICATION ROLES IN APPLICATION IDENTIFIER($APPLICATION_NAME);
SHOW SCHEMAS IN APPLICATION IDENTIFIER($APPLICATION_NAME);
SHOW OBJECTS IN APPLICATION IDENTIFIER($APPLICATION_NAME);

-- Validate app-owned schemas and objects.
SHOW TABLES IN APPLICATION IDENTIFIER($APPLICATION_NAME);
SHOW VIEWS IN APPLICATION IDENTIFIER($APPLICATION_NAME);
SHOW PROCEDURES IN APPLICATION IDENTIFIER($APPLICATION_NAME);
SHOW STREAMLITS IN APPLICATION IDENTIFIER($APPLICATION_NAME);

-- Optional targeted checks if your account supports querying from application objects directly.
-- Uncomment if needed after install:
--
-- SELECT * FROM COSTOPS_APP_DEV.COSTOPS_APP.ENTERPRISE_READINESS_VIEW;
-- SELECT COUNT(*) FROM COSTOPS_APP_DEV.COSTOPS_APP.ENTERPRISE_CONFIG_SNAPSHOT;
-- SELECT COUNT(*) FROM COSTOPS_APP_DEV.COSTOPS_APP.ENTERPRISE_USER_DIRECTORY;
-- SELECT COUNT(*) FROM COSTOPS_APP_DEV.COSTOPS_APP.ENTERPRISE_CONFIG_AUDIT_LOG;

-- Post-install grant for usage telemetry, if desired:
-- GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO APPLICATION COSTOPS_APP_DEV;
