-- CostOps Native App
-- Step 5: clean up after local validation
--
-- Replace the placeholders below before running.

USE ROLE ACCOUNTADMIN;

SET PACKAGE_DB = 'COSTOPS_NATIVE_DEV';
SET PACKAGE_SCHEMA = 'PACKAGE_SRC';
SET PACKAGE_STAGE = 'COSTOPS_STAGE';
SET APPLICATION_PACKAGE_NAME = 'COSTOPS_PKG';
SET APPLICATION_NAME = 'COSTOPS_APP_DEV';

DROP APPLICATION IF EXISTS IDENTIFIER($APPLICATION_NAME);

-- Optional deeper cleanup once you are completely done testing:
-- DROP APPLICATION PACKAGE IF EXISTS IDENTIFIER($APPLICATION_PACKAGE_NAME);
-- DROP STAGE IF EXISTS IDENTIFIER($PACKAGE_DB || '.' || $PACKAGE_SCHEMA || '.' || $PACKAGE_STAGE);
-- DROP SCHEMA IF EXISTS IDENTIFIER($PACKAGE_DB || '.' || $PACKAGE_SCHEMA);
-- DROP DATABASE IF EXISTS IDENTIFIER($PACKAGE_DB);
