RULE_CATALOG = [
    {
        "rule_id": "WH_AUTO_SUSPEND_HIGH",
        "category": "Warehouse",
        "rule": "Auto-suspend too high",
        "data_sources": "SHOW WAREHOUSES, WAREHOUSE_METERING_HISTORY",
        "output": "ALTER WAREHOUSE statement",
        "mvp": True,
    },
    {
        "rule_id": "WH_OVERSIZED",
        "category": "Warehouse",
        "rule": "Oversized warehouse",
        "data_sources": "QUERY_HISTORY, WAREHOUSE_METERING_HISTORY",
        "output": "Downsize recommendation with savings estimate",
        "mvp": True,
    },
    {
        "rule_id": "WH_IDLE_RUNTIME",
        "category": "Warehouse",
        "rule": "Idle warehouse runtime",
        "data_sources": "WAREHOUSE_METERING_HISTORY, QUERY_HISTORY",
        "output": "Suspend, resize, or retire recommendation",
        "mvp": True,
    },
    {
        "rule_id": "QUERY_FULL_SCAN",
        "category": "Query",
        "rule": "Full table scans",
        "data_sources": "QUERY_HISTORY",
        "output": "Pruning and filter recommendation",
        "mvp": True,
    },
    {
        "rule_id": "QUERY_SPILLAGE",
        "category": "Query",
        "rule": "High disk spillage",
        "data_sources": "QUERY_HISTORY",
        "output": "Rewrite or warehouse sizing recommendation",
        "mvp": True,
    },
    {
        "rule_id": "PIPELINE_FULL_REFRESH",
        "category": "Pipeline",
        "rule": "Full refresh pattern",
        "data_sources": "QUERY_HISTORY, TASK_HISTORY",
        "output": "Incremental load recommendation",
        "mvp": True,
    },
    {
        "rule_id": "TASK_FREQUENCY_HIGH",
        "category": "Task",
        "rule": "Task runs too frequently",
        "data_sources": "TASK_HISTORY",
        "output": "Schedule reduction recommendation",
        "mvp": True,
    },
    {
        "rule_id": "STORAGE_STALE_OBJECT",
        "category": "Storage",
        "rule": "Unused or stale table",
        "data_sources": "TABLES, ACCESS_HISTORY",
        "output": "Archive, drop, or owner-review recommendation",
        "mvp": True,
    },
    {
        "rule_id": "STORAGE_RETENTION_HIGH",
        "category": "Storage",
        "rule": "Retention too high",
        "data_sources": "INFORMATION_SCHEMA.TABLES",
        "output": "Retention reduction SQL",
        "mvp": True,
    },
    {
        "rule_id": "GOV_QUERY_TAG_MISSING",
        "category": "Governance",
        "rule": "Missing query tags",
        "data_sources": "QUERY_HISTORY",
        "output": "Cost attribution guidance",
        "mvp": True,
    },
]

